name: asadvpn
description: AsadVPN (UNLIMITED)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  device_info_plus: ^9.1.0
  url_launcher: ^6.1.14
  permission_handler: ^11.0.1
  flutter_localizations:
    sdk: flutter
  mobile_scanner: ^3.0.0

  flutter_v2ray:
    git:
      url: https://github.com/CuleFlaco/flutter_v2ray.git
      ref: main

dependency_overrides:
  flutter_v2ray:
    git:
      url: https://github.com/CuleFlaco/flutter_v2ray.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/lion.png"
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/icon/lion.png"
