name: Build APK with libbox

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        shell: bash
        run: |
          set -euxo pipefail
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.1.8937393" "cmdline-tools;latest"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> $GITHUB_ENV

      - name: Set up Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Build libbox.aar via gomobile
        shell: bash
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          set -euxo pipefail
          echo "Go version:"
          go version
          echo "Env:"
          go env

          # Ensure gomobile in PATH
          export GOBIN="$HOME/go/bin"
          export PATH="$GOBIN:$PATH"

          # gomobile & gobind (use latest; Go 1.24 required)
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile version || true

          # Initialize gomobile with the NDK
          gomobile init -ndk "$ANDROID_NDK_HOME"

          # Clone sing-box source (pin to a stable tag)
          git clone --depth 1 --branch v1.12.8 https://github.com/SagerNet/sing-box.git sing-box-src

          # Build libbox AAR
          mkdir -p android/app/libs
          cd sing-box-src/experimental/libbox

          # Some environments need GO111MODULE=on explicitly
          export GO111MODULE=on

          # Bind. -javapkg defines the Java/Kotlin package used by the AAR
          gomobile bind -target=android -javapkg io.nekohasekai.libbox -o $GITHUB_WORKSPACE/android/app/libs/libbox.aar

          ls -lah $GITHUB_WORKSPACE/android/app/libs/

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Flutter pub get
        shell: bash
        run: flutter pub get

      - name: Build APK (release)
        shell: bash
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk