name: Build libbox AAR and APK (pinned toolchain)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        shell: bash
        run: |
          yes | sdkmanager --licenses || true

      - name: Install Android SDK components
        shell: bash
        run: |
          set -eux
          # Modern platform for Flutter build + API 21 for gomobile + NDK r25
          sdkmanager --install "platform-tools" "platforms;android-34" "platforms;android-21" "build-tools;34.0.0" "ndk;25.1.8937393"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> $GITHUB_ENV
          ls -lah "$ANDROID_SDK_ROOT/ndk/" || true

      - name: Set up Go 1.20.14
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.14'

      - name: Build libbox.aar via pinned gomobile + older sing-box
        shell: bash
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          set -eux
          export GO111MODULE=on
          export PATH="$HOME/go/bin:$PATH"

          echo "Go version:"
          go version

          # 1) Clone golang/mobile and pin a commit before 2023-03-01
          git clone https://github.com/golang/mobile.git gomobile-src
          cd gomobile-src
          COMMIT=$(git rev-list -n 1 --before='2023-03-01' origin/master)
          git checkout "$COMMIT"
          echo "Pinned golang/mobile commit: $COMMIT"

          # 2) Install gomobile and gobind from pinned source
          go install ./cmd/gomobile
          go install ./cmd/gobind
          cd ..

          # 3) Do NOT run 'gomobile init' to avoid fetching latest gobind

          # 4) Clone older sing-box tag compatible with Go 1.20
          git clone --depth 1 --branch v1.8.7 https://github.com/SagerNet/sing-box.git sing-box-src

          # 5) Build libbox.aar targeting android API 21 (>=19 for NDK r25)
          mkdir -p android/app/libs
          cd sing-box-src/experimental/libbox
          gomobile bind -target=android -androidapi 21 -javapkg io.nekohasekai.libbox -o "$GITHUB_WORKSPACE/android/app/libs/libbox.aar"
          ls -lah "$GITHUB_WORKSPACE/android/app/libs/"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
