name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Clean everything
        run: |
          flutter clean
          rm -rf pubspec.lock
          rm -rf .dart_tool
          rm -rf ~/.pub-cache/git/

      - name: Show pubspec.yaml content
        run: |
          echo "=== PUBSPEC.YAML CONTENT ==="
          cat pubspec.yaml

      - name: Get dependencies (verbose)
        run: flutter pub get -v

      - name: Debug - Check what was downloaded
        run: |
          echo "=== CHECKING IF FLUTTER_V2RAY EXISTS ==="
          
          echo "--- In pubspec.lock ---"
          if [ -f "pubspec.lock" ]; then
            grep -A20 "flutter_v2ray:" pubspec.lock || echo "NOT FOUND in pubspec.lock!"
          fi
          
          echo "--- In .dart_tool/package_config.json ---"
          if [ -f ".dart_tool/package_config.json" ]; then
            cat .dart_tool/package_config.json | python3 -m json.tool | grep -A5 "flutter_v2ray" || echo "NOT FOUND in package_config.json!"
          fi
          
          echo "--- Flutter pub deps output ---"
          flutter pub deps | grep flutter_v2ray || echo "NOT FOUND in deps!"
          
          echo "--- Git cache ---"
          ls -la ~/.pub-cache/git/ || echo "No git cache"
          
          echo "--- Check if V2ray class exists in cached package ---"
          find ~/.pub-cache/git -name "flutter_v2ray.dart" -exec grep -l "class V2ray" {} \; || echo "V2ray class not found in cache"

      - name: Try importing manually to test
        run: |
          echo "=== Testing import ==="
          cat > test_import.dart << 'EOF'
          import 'package:flutter_v2ray/flutter_v2ray.dart';
          void main() {
            print('Import successful');
          }
          EOF
          dart test_import.dart || echo "Import failed"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
