name: Build APK with libbox

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Accept licenses (ignore Broken pipe after completion)
      - name: Accept SDK licenses
        shell: bash
        run: |
          yes | sdkmanager --licenses || true

      # Install required SDK packages (no piping; licenses already accepted)
      - name: Install Android SDK components
        shell: bash
        run: |
          set -eux
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.1.8937393"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> $GITHUB_ENV
          ls -lah $ANDROID_SDK_ROOT/ndk/ || true

      - name: Set up Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Build libbox.aar via gomobile
        shell: bash
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          set -eux
          export PATH="$HOME/go/bin:$PATH"
          export GO111MODULE=on

          go version

          # Install gomobile & gobind
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest

          # Initialize gomobile (no -ndk; it will find NDK via env)
          gomobile init

          # Clone sing-box source (stable tag)
          git clone --depth 1 --branch v1.12.8 https://github.com/SagerNet/sing-box.git sing-box-src

          # Build libbox AAR
          mkdir -p android/app/libs
          cd sing-box-src/experimental/libbox
          gomobile bind -target=android -javapkg io.nekohasekai.libbox -o "$GITHUB_WORKSPACE/android/app/libs/libbox.aar"

          ls -lah "$GITHUB_WORKSPACE/android/app/libs/"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
