name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Clean everything
        run: |
          flutter clean
          rm -rf pubspec.lock
          rm -rf .dart_tool
          rm -rf ~/.pub-cache/hosted/pub.dev/flutter_v2ray-*

      - name: Get dependencies
        run: flutter pub get -v

      - name: Check what was downloaded
        run: |
          echo "=== PUBSPEC.LOCK ==="
          cat pubspec.lock | grep -A15 "flutter_v2ray:"
          echo "=== PACKAGE CONFIG ==="
          cat .dart_tool/package_config.json | python3 -m json.tool | grep -A8 "flutter_v2ray"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
